# Generated by Django 2.2.19 on 2021-03-03 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='assets/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('transfer_info', models.TextField()),
                ('lodge_info', models.TextField()),
                ('specialty_info', models.TextField()),
                ('sights_info', models.TextField()),
                ('other_info', models.TextField()),
                ('cover_image', models.ImageField(upload_to='city_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='travelhub.Category')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('area', models.CharField(choices=[('0', 'アジア'), ('1', 'オセアニア'), ('2', '北アメリカ'), ('3', '中南アメリカ'), ('4', 'ヨーロッパ'), ('5', '中東'), ('6', 'アフリカ')], max_length=10)),
                ('official_language', models.CharField(max_length=50)),
                ('english_level', models.CharField(choices=[('3', '公用語'), ('2', '大体通じる'), ('1', '観光地のみ通じる'), ('0', '通じない')], max_length=10)),
                ('currency', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=50)),
                ('Ja_enbassy', models.CharField(max_length=50)),
                ('price_level', models.CharField(choices=[('2', '日本より高い'), ('1', '日本と同じくらい'), ('0', '日本より安い')], max_length=10)),
                ('place_info', models.TextField()),
                ('city_info', models.TextField()),
                ('tour_info', models.TextField()),
                ('cover_image', models.ImageField(upload_to='country_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='travelhub.Category')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='travelhub.City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='travelhub.Country')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='tags',
            field=models.ManyToManyField(blank=True, to='travelhub.Tag'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travelhub.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='tags',
            field=models.ManyToManyField(blank=True, to='travelhub.Tag'),
        ),
    ]
