# Generated by Django 2.2.19 on 2021-03-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='Ja_enbassy',
            new_name='Ja_embassy',
        ),
    ]
