# Generated by Django 2.2.19 on 2021-03-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelhub', '0002_auto_20210304_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('access', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('opening_hours', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('image', models.ImageField(upload_to='place_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='travelhub.Category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='travelhub.City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='travelhub.Country')),
                ('tags', models.ManyToManyField(blank=True, to='travelhub.Tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
