# Generated by Django 2.2.19 on 2021-03-11 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelhub', '0005_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelhub.City', verbose_name='対象記事'),
        ),
    ]
